{% set name = "qc3C" %}
{% set version = "v0.5rc1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: "https://github.com/cerebis/{{ name }}.git"
  sha256: 68adc6dede8e57deb4b3f1443240e140445436221e566d8da13d7173b13e921c

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:

  build:
    - python {{ python }}
    - setuptools

  host:
    - pip
    - python {{ python }}
    - cython

  run:
    - python {{ python }}
    - astropy
    - biopython<1.77
    - jellyfish
    - json2html
    - leven
    - numba
    - numpy
    - pandas
    - psutil
    - pysam
    - scipy
    - simplejson
    - tqdm

test:
  imports:
    - qc3C

about:
  home: "https://github.com/cerebis/qc3C"
  license: GNU Affero General Public License v3.0
  license_family: AGPL
  license_file: 
  summary: "Hi-C quality control"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - cerebis

