{% set name = "qc3C" %}
{% set version = "v0.5rc9" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  git_url: "https://github.com/cerebis/{{ name }}.git"
  sha256: 9b5c0914edef9b7b4b2b687340e4836bd0b84ff1d4885014323d056e40b3fc5f

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:

  build:
    - python {{ python }}
    - setuptools

  host:
    - pip
    - python {{ python }}
    - cython

  run:
    - python {{ python }}
    - astropy<4.1
    - biopython<1.77
    - jellyfish
    - json2html
    - leven
    - numba
    - numpy
    - pandas
    - psutil
    - pysam
    - scipy
    - simplejson
    - tqdm

test:
  imports:
    - qc3C
  source_files:
    - tests/test_utils.py
    - tests/data/10seq.fa
    - tests/data/10seq.fa.gz
    - tests/data/10seq.fq
    - tests/data/10seq.fq.gz
    - tests/data/test.fq.gz
  requires:
    - pytest
  commands:
    - pytest tests

about:
  home: "https://github.com/cerebis/qc3C"
  license: GNU Affero General Public License v3.0
  license_family: AGPL
  license_file: 
  summary: "Hi-C quality control"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - cerebis
